### ISSUE TITLE
Can't build

### ISSUE THREAD

**Issue by bildlich** [mike-schultz/materialette#5]
When I run `npm run build`, the build fails. The content of npm-debug.log:

```
0 info it worked if it ends with ok
1 verbose cli [ '/Users/bildlich/.nvm/versions/node/v6.8.1/bin/node',
1 verbose cli   '/Users/bildlich/.nvm/versions/node/v6.8.1/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@3.10.8
3 info using node@v6.8.1
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle materialette@1.0.0~prebuild: materialette@1.0.0
6 silly lifecycle materialette@1.0.0~prebuild: no script for prebuild, continuing
7 info lifecycle materialette@1.0.0~build: materialette@1.0.0
8 verbose lifecycle materialette@1.0.0~build: unsafe-perm in lifecycle true
9 verbose lifecycle materialette@1.0.0~build: PATH: /Users/bildlich/.nvm/versions/node/v6.8.1/lib/node_modules/npm/bin/node-gyp-bin:/Users/bildlich/Development/materialette/node_modules/.bin:/Users/bildlich/.nvm/versions/node/v6.8.1/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin
10 verbose lifecycle materialette@1.0.0~build: CWD: /Users/bildlich/Development/materialette
11 silly lifecycle materialette@1.0.0~build: Args: [ '-c', 'npm run build:macos' ]
12 silly lifecycle materialette@1.0.0~build: Returned: code: 1  signal: null
13 info lifecycle materialette@1.0.0~build: Failed to exec build script
14 verbose stack Error: materialette@1.0.0 build: `npm run build:macos`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/Users/bildlich/.nvm/versions/node/v6.8.1/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/Users/bildlich/.nvm/versions/node/v6.8.1/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid materialette@1.0.0
16 verbose cwd /Users/bildlich/Development/materialette
17 error Darwin 15.6.0
18 error argv "/Users/bildlich/.nvm/versions/node/v6.8.1/bin/node" "/Users/bildlich/.nvm/versions/node/v6.8.1/bin/npm" "run" "build"
19 error node v6.8.1
20 error npm  v3.10.8
21 error code ELIFECYCLE
22 error materialette@1.0.0 build: `npm run build:macos`
22 error Exit status 1
23 error Failed at the materialette@1.0.0 build script 'npm run build:macos'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the materialette package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     npm run build:macos
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs materialette
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls materialette
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by mike-schultz** [comment]
Probably was due to `electron-packager` not being in the package.json. Master has an updated package.json now - let me know if that worked for you.
